clc;
clear all;
close all;
Fs = 1000;
T = 1;
t = 0:1/Fs:T-1/Fs;
f_signal = 10;
A_signal = 1;
signal1 = A_signal * sin(2*pi*f_signal*t);
signal2 = A_signal * square(2*pi*f_signal*t);
SNR_dB1 = 15;
SNR_dB2 = 0;
SNR_dB3 = -5;
noise_power1 = var(signal1) / (10^(SNR_dB1/10));
noise_power2 = var(signal1) / (10^(SNR_dB2/10));
noise_power3 = var(signal1) / (10^(SNR_dB3/10));
noise_power4 = var(signal2) / (10^(SNR_dB1/10));
noise1 = sqrt(noise_power1) * randn(size(t));
noise2 = sqrt(noise_power2) * randn(size(t));
noise3 = sqrt(noise_power3) * randn(size(t));
noise4 = sqrt(noise_power4) * randn(size(t));
noisy_signal1 = signal1 + noise1;
noisy_signal2 = signal1 + noise2;
noisy_signal3 = signal1 + noise3;
noisy_signal4 = signal2 + noise4;
figure;
subplot(2,2,1);
plot(t,signal1);
title('Original Sinusoidal Signal');
subplot(2,2,2);
plot(t,noisy_signal1);
title(['Noisy Signal (SNR = ' num2str(SNR_dB1) ' dB)']);xlabel('Time (seconds)');
subplot(2,2,3);
plot(t,noisy_signal2);
title(['Noisy Signal (SNR = ' num2str(SNR_dB2) ' dB)']);
xlabel('Time (seconds)');
subplot(2,2,4);
plot(t,noisy_signal3);
title(['Noisy Signal (SNR = ' num2str(SNR_dB3) ' dB)']);
xlabel('Time (seconds)');
figure;
subplot(2,1,1);
plot(t,signal2);
title('Original Square Signal');
subplot(2,1,2);
plot(t,noisy_signal4);
title(['Noisy Signal (SNR = ' num2str(SNR_dB1) ' dB)']);
xlabel('Time (seconds)');
