clc;
clear;
close all;
Pt = 1;
Gt = 1;
Gr = 1;
lambda = 0.125;
ht = 10;
hr = 2;
d = linspace(1, 1000, 1000);
Pr_friis = (Pt * Gt * Gr * (lambda.^2)) ./ ((4 * pi * d).^2 );
Pr_two_ray = (Pt * Gt * Gr * (ht^2 * hr^2)) ./ (d.^4);
figure;
semilogy(d, Pr_friis, 'r', 'LineWidth', 2); hold on;
semilogy (d, Pr_two_ray, 'b', 'LineWidth', 2);
grid on;
xlabel('Distance (m)');
ylabel('Received Power (W)');
title('Two-Ray Ground Reflection Model vs Friis Free-Space Model');
legend('Friis Free-Space', 'Two-Ray Model');
